// ── Honeypot config ─────────────────────────────────────────
// Add sentences freely — one per line, nothing else to change.
// Responses are picked at random on every hit.

const responses = [
  // User-defined
  'Nice try diddy 🛢️🫣',
  'Sabrina Carpenter said no 💅🚫',
  'Nice try lil bro 😭🙏',

  // Bonus bangers
  'Bro really thought he was a hacker 💀',
  'You shall not pass 🧙',
  'Sir, this is a Wendy\'s 🍔',
  'The database is in another castle 🏰',
  'lmao nice try bestie',
  'Not today satan 😇',
  'This endpoint is sponsored by skill issue',
  'Error 420: go touch some grass 🌱',
  'Your hacking skills have been rated: 0/10',
  'Congrats, you found absolutely nothing 🎉',
  'mom said it\'s my turn on the Xbox 🎮',
  'Have you tried asking nicely instead?',
  'This file does not spark joy. Goodbye. ✨',
  'Bruh.',
  'FBI open up! (jk, but also stop) 🚔',
  'Caught you lacking fr fr 📸',
  'W try, L result',
  'Did you really think it would be that easy?',
  'No cap this ain\'t it chief 🧢',
  'The audacity 💅',
  'Try harder (you won\'t)',

  // Fresh drops 🆕
  'Plot twist: there was never anything here 🎬',
  'Scanning intensifies... finding nothing intensifies 📡',
  'You\'ve activated my trap card 🃏',
  'Imagine port-scanning a coffee machine ☕',
  'This is a honeypot and you, my friend, are the bee 🐝',
  'Your IP just got a participation trophy 🏆',
  'curl -s yourself out of here',
  'Loading secrets... 0% ... forever ⏳',
  'Achievement unlocked: Wasted Your Time 🎯',
  'I see you\'ve chosen violence today. Bold. ⚔️',
  'Beep boop, access denied, have a nice day 🤖',
  'You wouldn\'t download a database',
  'Skill check failed (rolled a natural 1) 🎲',
  '404: dignity not found',
  'This path leads to a dead end and mild embarrassment',
  'Touch grass speedrun any% 🌿',
  'Nice user-agent, did your bot pick it? 🤡',
  'We ran out of secrets, try the gift shop 🛍️',
  'Respectfully: lol, and also, no',
  'Your request has been forwarded to /dev/null 🗑️',
  'Hackerman.exe has stopped working',
  'You found the secret room! It is empty. 📦',
  'Logging your attempt for the company newsletter 📰',
  'That\'s a paddlin\'',
  'Server says: absolutely not, with love ❤️',
  'You may not pass, but you may feel embarrassed 🙃',
  'Certified L moment 📉',
  'This honeypot runs on copium and your tears 😭',
  'Even my grandma scans better than this 👵',
];

// ── 🪤 Paths to trap ───────────────────────────────────────────
// All HTTP methods are caught. Add any path you want to troll.

const paths = [
  // 🔍 Classic scanner probes
  '/.env',
  '/.env.local',
  '/.env.production',
  '/.env.dev',
  '/.env.development',
  '/.env.staging',
  '/.env.backup',
  '/.env.bak',
  '/.env.old',
  '/.env.save',
  '/.git/config',
  '/.git/HEAD',
  '/.git/index',
  '/.git/logs/HEAD',
  '/.svn/entries',
  '/.svn/wc.db',
  '/.hg/store',
  '/.DS_Store',
  '/.htaccess',
  '/.htpasswd',
  '/wp-admin',
  '/wp-admin/admin-ajax.php',
  '/wp-login.php',
  '/wordpress/wp-login.php',
  '/wp-content/debug.log',
  '/wp-config.php',
  '/wp-config.php.bak',
  '/xmlrpc.php',
  '/readme.html',
  '/license.txt',
  '/phpmyadmin',
  '/phpMyAdmin',
  '/pma',
  '/adminer',
  '/adminer.php',
  '/config.php',
  '/configuration.php',
  '/web.config',
  '/settings.py',
  '/database.yml',
  '/secrets.yml',
  '/credentials.json',
  '/secrets.json',
  '/backup.zip',
  '/backup.tar.gz',
  '/backup.sql',
  '/dump.sql',
  '/db.sql',
  '/database.sql',
  '/site.zip',
  '/www.zip',
  '/shell',
  '/shell.php',
  '/c99.php',
  '/r57.php',
  '/cmd',
  '/cmd.php',
  '/console',
  '/info.php',
  '/phpinfo.php',
  '/test.php',
  '/actuator',
  '/actuator/env',
  '/actuator/health',
  '/actuator/heapdump',
  '/server-status',
  '/server-info',
  '/metrics',
  '/debug/vars',

  // 🛡️ Credentials & key files
  '/.aws/credentials',
  '/.aws/config',
  '/.ssh/id_rsa',
  '/.ssh/id_rsa.pub',
  '/.ssh/authorized_keys',
  '/id_rsa',
  '/.npmrc',
  '/.dockercfg',
  '/.docker/config.json',
  '/.vscode/sftp.json',
  '/sftp-config.json',
  '/.idea/workspace.xml',
  '/.travis.yml',
  '/.gitlab-ci.yml',
  '/.netrc',
  '/private.key',
  '/server.key',
  '/id_ed25519',

  // 🌐 API honeypots
  '/api/secret',
  '/api/secrets',
  '/api/credentials',
  '/api/tokens',
  '/api/token',
  '/api/debug',
  '/api/config',
  '/api/configuration',
  '/api/backup',
  '/api/dump',
  '/api/private',
  '/api/internal',
  '/api/system',
  '/api/export',
  '/api/env',
  '/api/.env',
  '/api/admin',
  '/api/admin/dump',
  '/api/admin/passwords',
  '/api/admin/secrets',
  '/api/admin/login',
  '/api/users/export',
  '/api/users/all',
  '/api/database',
  '/api/db',
  '/api/keys',
  '/api/apikeys',
  '/api/v1/admin',
  '/api/v1/users',
  '/api/v1/secrets',
  '/api/v2/admin',
  '/api/health/debug',

  // 🚪 Admin & login panels
  '/admin',
  '/admin/',
  '/admin.php',
  '/admin/login',
  '/admin/index.php',
  '/administrator',
  '/administrator/index.php',
  '/login',
  '/login.php',
  '/user/login',
  '/manager/html',
  '/manager/status',
  '/jenkins',
  '/jenkins/login',
  '/jmx-console',
  '/solr/',
  '/kibana',
  '/grafana/login',
  '/.well-known/security.txt',

  // 🧩 Framework-specific traps
  '/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php',
  '/telescope/requests',
  '/_profiler/phpinfo',
  '/_ignition/execute-solution',
  '/wp-json/wp/v2/users',
  '/graphql',
  '/graphiql',
  '/swagger-ui.html',
  '/swagger.json',
  '/api/swagger.json',
  '/api-docs',
  '/v2/api-docs',

  // 📡 Router / appliance probes (classic botnet targets)
  '/cgi-bin/',
  '/cgi-bin/luci',
  '/HNAP1/',
  '/boaform/admin/formLogin',
  '/remote/login',
  '/owa/auth/logon.aspx',
  '/autodiscover/autodiscover.xml',
  '/Telerik.Web.UI.WebResource.axd',
];

module.exports = { responses, paths };